### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by dilne** [AntiAnti/SimplePyTorch#4]
Hi, many thanks for this awesome repo. I have been trying multiple methods to get TensorFlow to work in UE4 and it is a nightmare, so I'm grateful for this repo.

I'm asking if you could please supply a quick tutorial for using SimplePyTorch now that I have successfully integrated the plugin into my project.

How can I use SimplePyTorch for inference? For example:
1. Uploading my model from a file
2. Making a prediction using the loaded model

If I can then get it working I'd love to create a YouTube tutorial for SimplePyTorch to help out others and increase interest in this very useful repo. It would be great if I could fulfil my main aim of creating a CNN inside UE4. Many thanks.

**Comment by AntiAnti** [comment]
Maybe this example can help https://drive.google.com/file/d/1AwLZdp2ygFlpel0hzGxgUz8_lGWnBKFl/view?usp=sharing
